# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-31 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7701')),
            ],
            options={
                'verbose_name': '\u7701',
                'verbose_name_plural': '\u7701',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u533b\u9662\u540d\u79f0')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5177\u4f53\u5730\u5740')),
                ('manager', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5927\u533a\u7ecf\u7406')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u56fe\u6587\u94fe\u63a5')),
                ('confirm', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786e\u8ba4\u5c31\u8bca\u77ed\u4fe1')),
                ('three', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u524d\u4e09\u5929\u77ed\u4fe1')),
                ('inday', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5f53\u5929\u63d0\u9192\u77ed\u4fe1')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apoint.Area', verbose_name='\u5bf9\u5e94\u7701')),
            ],
            options={
                'verbose_name': '\u533b\u9662',
                'verbose_name_plural': '\u533b\u9662',
            },
        ),
        migrations.CreateModel(
            name='IllnessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200, verbose_name='\u75c5\u60c5\u56fe\u7247\u94fe\u63a5')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(blank=True, max_length=100, null=True, verbose_name='openid')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u60a3\u8005\u59d3\u540d')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u624b\u673a')),
                ('wantTime', models.DateTimeField(null=True, verbose_name='\u5c31\u8bca\u65f6\u95f4')),
                ('number', models.IntegerField(default=0, verbose_name='\u6cbb\u7597\u6b21\u6570')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='\u75c5\u60c5\u63cf\u8ff0')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('nextcalldate', models.DateField(null=True, verbose_name='\u4e0b\u6b21\u7535\u8bdd\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(1, '\u672a\u8ba4\u9886'), (2, '\u5df2\u8ba4\u9886\u672a\u786e\u8ba4'), (3, '\u786e\u8ba4\u53bb\u5c31\u8bca'), (4, '\u786e\u8ba4\u4e0d\u5c31\u8bca'), (5, '\u5ef6\u671f\u9884\u7ea6'), (6, '\u5df2\u5b89\u6392\u6cbb\u7597'), (7, '\u5b8c\u6210\u9996\u6b21\u968f\u8bbf'), (8, '\u5b8c\u621015\u65e5\u968f\u8bbf'), (9, '\u5b8c\u621030\u65e5\u968f\u8bbf'), (10, '\u5b8c\u621045\u65e5\u968f\u8bbf'), (11, '\u5ef6\u540e\u6cbb\u7597'), (12, '\u6682\u505c\u8ddf\u8fdb'), (13, '\u8f6c\u9662'), (14, '\u786e\u8ba4\u672a\u5230\u8bca')], default=1, verbose_name='\u5f53\u524d\u72b6\u6001')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apoint.Area', verbose_name='\u7701')),
            ],
            options={
                'verbose_name': '\u60a3\u8005\u8ba2\u5355',
                'verbose_name_plural': '\u60a3\u8005\u8ba2\u5355',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(1, '\u672a\u8ba4\u9886'), (2, '\u5df2\u8ba4\u9886\u672a\u786e\u8ba4'), (3, '\u786e\u8ba4\u53bb\u5c31\u8bca'), (4, '\u786e\u8ba4\u4e0d\u5c31\u8bca'), (5, '\u5ef6\u671f\u9884\u7ea6'), (6, '\u5df2\u5b89\u6392\u6cbb\u7597'), (7, '\u5b8c\u6210\u9996\u6b21\u968f\u8bbf'), (8, '\u5b8c\u621015\u65e5\u968f\u8bbf'), (9, '\u5b8c\u621030\u65e5\u968f\u8bbf'), (10, '\u5b8c\u621045\u65e5\u968f\u8bbf'), (11, '\u5ef6\u540e\u6cbb\u7597'), (12, '\u6682\u505c\u8ddf\u8fdb'), (13, '\u8f6c\u9662'), (14, '\u786e\u8ba4\u672a\u5230\u8bca')], default=0, verbose_name='\u72b6\u6001')),
                ('remark', models.CharField(max_length=1000, null=True, verbose_name='\u63cf\u8ff0')),
                ('is_operation', models.BooleanField(default=False, verbose_name='\u662f\u5426\u64cd\u4f5c')),
                ('nextcalldate', models.DateField(null=True, verbose_name='\u4e0b\u6b21\u7535\u8bdd\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u786e\u8ba4\u4e0e\u5907\u5fd8',
                'verbose_name_plural': '\u786e\u8ba4\u4e0e\u5907\u5fd8',
            },
        ),
        migrations.CreateModel(
            name='ZJUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('usertype', models.IntegerField(choices=[(1, '\u5ba2\u670d'), (2, '\u9500\u552e'), (3, '\u7ba1\u7406\u5458')], default=1, verbose_name='\u7528\u6237\u7c7b\u578b')),
                ('phone', models.CharField(max_length=50, verbose_name='\u624b\u673a\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='SalesUser',
            fields=[
                ('zjuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apoint.ZJUser')),
                ('openid', models.CharField(blank=True, max_length=100, null=True, verbose_name='openid')),
                ('email', models.CharField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('is_cert', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8ba4\u8bc1')),
            ],
            options={
                'verbose_name': '\u5458\u5de5',
                'verbose_name_plural': '\u5458\u5de5',
            },
            bases=('apoint.zjuser',),
        ),
        migrations.AddField(
            model_name='zjuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='apoint.ZJUser', verbose_name='\u64cd\u4f5c\u4eba'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoint.Order', verbose_name='\u6240\u5c5e\u9884\u7ea6'),
        ),
        migrations.AddField(
            model_name='order',
            name='custome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_custom', to='apoint.ZJUser', verbose_name='\u6240\u5c5e\u5ba2\u670d'),
        ),
        migrations.AddField(
            model_name='order',
            name='wanthospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoint.Hospital', verbose_name='\u533b\u9662\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='illnessimage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apoint.Order', verbose_name='\u4e0a\u4f20\u4eba'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apoint.SalesUser', verbose_name='\u5bf9\u5e94\u7684\u9500\u552e'),
        ),
    ]
